name: docker_publish

on:
  push:
    tags:
      - 'v*'
  schedule:
    - cron:  '0 3 * * 1'

  workflow_dispatch:

# Sets the permissions granted to the GITHUB_TOKEN for the actions in this job.
permissions:
  contents: read
  packages: write

jobs:
  docker-alpine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup docker
        id: setup
        uses: ./.github/workflows/docker-reused-setup-steps
        with:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
          tag: alpine

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          target: final
          tags: ${{ steps.setup.outputs.tags }}
          labels: ${{ steps.setup.outputs.labels }}
          build-args: |
            VERSION=${{ github.head_ref || github.ref_name }}
            RELEASE=${{ github.run_number }}
          platforms: linux/amd64,linux/arm64
          # Cache to regietry instead of gha to avoid the capacity limit.
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ytarchive:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ytarchive:cache,mode=max
          sbom: true
          provenance: true

  docker-ubi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup docker
        id: setup
        uses: ./.github/workflows/docker-reused-setup-steps
        with:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
          tag: ubi

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./ubi.Dockerfile
          push: true
          target: final
          tags: ${{ steps.setup.outputs.tags }}
          labels: ${{ steps.setup.outputs.labels }}
          build-args: |
            VERSION=${{ github.head_ref || github.ref_name }}
            RELEASE=${{ github.run_number }}
          platforms: linux/amd64,linux/arm64
          # Cache to regietry instead of gha to avoid the capacity limit.
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ytarchive:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ytarchive:cache,mode=max
          sbom: true
          provenance: true

  docker-distroless:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup docker
        id: setup
        uses: ./.github/workflows/docker-reused-setup-steps
        with:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
          tag: distroless

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./distroless.Dockerfile
          push: true
          target: final
          tags: ${{ steps.setup.outputs.tags }}
          labels: ${{ steps.setup.outputs.labels }}
          build-args: |
            VERSION=${{ github.head_ref || github.ref_name }}
            RELEASE=${{ github.run_number }}
          platforms: linux/amd64,linux/arm64
          # Cache to regietry instead of gha to avoid the capacity limit.
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ytarchive:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ytarchive:cache,mode=max
          sbom: true
          provenance: true
