name: docker_publish

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }},ghcr.io/${{ github.repository }},quay.io/${{ github.repository }}
          # set latest tag for default branch
          tags: |
            type=ref,event=tag
            type=ref,suffix=-alpine,event=tag
            type=raw,value=latest
  
      - name: Docker meta-ubi
        id: meta-ubi
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }},ghcr.io/${{ github.repository }},quay.io/${{ github.repository }}
          # set latest tag for default branch
          tags: |
            type=ref,suffix=-ubi,event=tag

      - name: Docker meta-distroless
        id: meta-distroless
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }},ghcr.io/${{ github.repository }},quay.io/${{ github.repository }}
          # set latest tag for default branch
          tags: |
            type=ref,suffix=-distroless,event=tag

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Create a Access Token and save it as as Actions secret
      # https://hub.docker.com/settings/security
      # DOCKERHUB_USERNAME
      # DOCKERHUB_TOKEN
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Create a Access Token with `read:packages` and `write:packages` scopes
      # CR_PAT
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Login to Quay Container Registry
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          target: final
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: VERSION=${{ github.head_ref || github.ref_name }}
          platforms: linux/amd64,linux/arm64

      - name: Build and push-ubi
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.ubi
          push: true
          target: final
          tags: ${{ steps.meta-ubi.outputs.tags }}
          labels: ${{ steps.meta-ubi.outputs.labels }}
          build-args: VERSION=${{ github.head_ref || github.ref_name }}
          platforms: linux/amd64,linux/arm64

      - name: Build and push-distroless
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.distroless
          push: true
          target: final
          tags: ${{ steps.meta-distroless.outputs.tags }}
          labels: ${{ steps.meta-distroless.outputs.labels }}
          build-args: VERSION=${{ github.head_ref || github.ref_name }}
          platforms: linux/amd64,linux/arm64
