name: docker_publish

on:
  push:
    tags:
      - "v*"
  schedule:
    - cron: "0 3 * * 1"

  workflow_dispatch:

# Sets the permissions granted to the GITHUB_TOKEN for the actions in this job.
permissions:
  id-token: write
  attestations: write
  contents: read
  packages: write

jobs:
  docker-alpine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Setup docker
        id: setup
        uses: ./.github/workflows/docker-reused-setup-steps
        with:
          DOCKERHUB_ORGANIZATION_NAME : ${{ secrets.DOCKERHUB_ORGANIZATION_NAME }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          tag: alpine

      - name: Build and push
        id: build_push_alpine
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          target: final
          tags: ${{ steps.setup.outputs.tags }}
          labels: ${{ steps.setup.outputs.labels }}
          build-args: |
            VERSION=${{ github.head_ref || github.ref_name }}
            RELEASE=${{ github.run_number }}
          platforms: linux/amd64,linux/arm64
          sbom: true
          provenance: true

      - name: Attest DockerHub image (alpine)
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/${{ inputs.DOCKERHUB_ORGANIZATION_NAME }}/ytarchive
          subject-digest: ${{ steps.build_push_alpine.outputs.digest }}

      - name: Attest GHCR image (alpine)
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/ytarchive
          subject-digest: ${{ steps.build_push_alpine.outputs.digest }}

  docker-ubi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Setup docker
        id: setup
        uses: ./.github/workflows/docker-reused-setup-steps
        with:
          DOCKERHUB_ORGANIZATION_NAME : ${{ secrets.DOCKERHUB_ORGANIZATION_NAME }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          tag: ubi

      - name: Build and push
        id: build_push_ubi
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./ubi.Dockerfile
          push: true
          target: final
          tags: ${{ steps.setup.outputs.tags }}
          labels: ${{ steps.setup.outputs.labels }}
          build-args: |
            VERSION=${{ github.head_ref || github.ref_name }}
            RELEASE=${{ github.run_number }}
          platforms: linux/amd64,linux/arm64
          sbom: true
          provenance: true

      - name: Attest DockerHub image (ubi)
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/${{ inputs.DOCKERHUB_ORGANIZATION_NAME }}/ytarchive
          subject-digest: ${{ steps.build_push_ubi.outputs.digest }}

      - name: Attest GHCR image (ubi)
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/ytarchive
          subject-digest: ${{ steps.build_push_ubi.outputs.digest }}

  docker-distroless:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Setup docker
        id: setup
        uses: ./.github/workflows/docker-reused-setup-steps
        with:
          DOCKERHUB_ORGANIZATION_NAME : ${{ secrets.DOCKERHUB_ORGANIZATION_NAME }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          tag: distroless

      - name: Build and push
        id: build_push_distroless
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./distroless.Dockerfile
          push: true
          target: final
          tags: ${{ steps.setup.outputs.tags }}
          labels: ${{ steps.setup.outputs.labels }}
          build-args: |
            VERSION=${{ github.head_ref || github.ref_name }}
            RELEASE=${{ github.run_number }}
          platforms: linux/amd64,linux/arm64
          sbom: true
          provenance: true

      - name: Attest DockerHub image (distroless)
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/${{ inputs.DOCKERHUB_ORGANIZATION_NAME }}/ytarchive
          subject-digest: ${{ steps.build_push_distroless.outputs.digest }}

      - name: Attest GHCR image (distroless)
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/ytarchive
          subject-digest: ${{ steps.build_push_distroless.outputs.digest }}

